trigger: none
pr: none

pool:
  vmImage: windows-latest

parameters:
  - name: deployEnvironmentVariables
    displayName: Deploy Environment Variables ?
    type: boolean
    default: true
  - name: deployMainSolution
    displayName: Deploy Main Solution ?
    type: boolean
    default: true
  - name: deployFlowsSolution
    displayName: Deploy Flows Solution ?
    type: boolean
    default: true
  - name: deployPluginsSolution
    displayName: Deploy Plugins Solution ?
    type: boolean
    default: true
  - name: deployDataMigration
    displayName: Migrate Data ?
    type: boolean
    default: true

variables:
  solution: "**/*.sln"
  buildPlatform: "Any CPU"
  buildConfiguration: "Release"
  branch: "development_R3"

resources:
  repositories:
    - repository: he-invst-deployment
      type: git
      name: "Investments Programme/he-invst-deployment"
      ref: "development_R3"
  pipelines:
    - pipeline: BuildPipeline
      source: "Loans - CRM - Build"
      trigger: none

stages:
  - template: crm-deployment-pipelines/loans-crm-deploy-nonprod.yml@he-invst-deployment
    parameters:
      artifactLocationPipeline: BuildPipeline
      deployEnvironmentVariables: "${{ parameters.deployEnvironmentVariables }}"
      deployMainSolution: "${{ parameters.deployMainSolution }}"
      deployFlowsSolution: "${{ parameters.deployFlowsSolution }}"
      deployPluginsSolution: "${{ parameters.deployPluginsSolution }}"
      deployDataMigration: "${{ parameters.deployDataMigration }}"
