# Loans-CRM-Deploy-Upgrade

trigger: none
pr: none

pool:
  vmImage: windows-latest

parameters:
- name: UseUpgrade
  displayName: Upgrade ?
  type: boolean
  default: true

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  branch: 'master'


resources:
  repositories:
  - repository: he-invst-deployment
    type: git
    name: 'Investments Programme/he-invst-deployment'
    ref: 'stg2-deploy'

stages:
- template: crm-deployment-pipelines/loans-crm-build-export.yml@he-invst-deployment
- template: crm-deployment-pipelines/loans-crm-deploy.yml@he-invst-deployment
