# Loans-CRM-Deploy-Upgrade
schedules:
- cron: '0 23 * * 1,2,3,4,5'
  displayName: AHP - CRM - Deploy - Upgrade - Automatic night Deploy
  branches:
    include:
    - main
    
trigger: none
pr: none

pool: 
  vmImage: windows-latest

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  branch: 'master'


resources:
  repositories:
  - repository: he-invst-deployment
    type: git
    name: 'Investments Programme/he-invst-deployment'
    ref: 'main'

stages:
- template: crm-deployment-pipelines/loans-crm-build-export.yml@he-invst-deployment
- template: crm-deployment-pipelines/loans-crm-upgrade.yml@he-invst-deployment