#pragma warning disable CS1591
// Code Generated by DLaB.ModelBuilderExtensions
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Do they have a budget?
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum BudgetStatus
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CanBuy = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MayBuy = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NoCommittedBudget = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		WillBuy = 3,
	}
}
#pragma warning restore CS1591
