#pragma warning disable CS1591
// Code Generated by DLaB.ModelBuilderExtensions
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdynmkt_PlaceholderType
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Condition = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		List = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Token = 1,
	}
}
#pragma warning restore CS1591
