#pragma warning disable CS1591
// Code Generated by DLaB.ModelBuilderExtensions
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Summarize By WBS Node Level
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_wbsnodelevel
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		LeafNode = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Level1Phase = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Level2Summary = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		None = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Root = 1,
	}
}
#pragma warning restore CS1591
