#pragma warning disable CS1591
// Code Generated by DLaB.ModelBuilderExtensions
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Event Metadata Integration Status
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdynmkt_eventmetadataIntegrationStatus
	{
		
		/// <summary>
		/// Integrated status
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Integrated = 534120001,
		
		/// <summary>
		/// Not Integrated status
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NotIntegrated = 534120002,
		
		/// <summary>
		/// Unknown integration status
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Unknown = 534120000,
	}
}
#pragma warning restore CS1591
