#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HE.Investments.Common.CRM.Model
{
	
	
	/// <summary>
	/// Select an activity type
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum activity_typecode
	{
		
		/// <summary>
		/// Appointment
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Appointment = 4201,
		
		/// <summary>
		/// Email
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Email = 4202,
		
		/// <summary>
		/// Fax
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Fax = 4204,
		
		/// <summary>
		/// Letter
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Letter = 4207,
		
		/// <summary>
		/// Phone Call
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PhoneCall = 4210,
	}
}
#pragma warning restore CS1591
