#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HE.Investments.Common.CRM.Model
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum AIPluginType
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Dataverse = 0,
	}
}
#pragma warning restore CS1591
