#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HE.Investments.Common.CRM.Model
{
	
	
	/// <summary>
	/// Field used by PWC. Notice that it has more options that the Region OptionSet.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum he_GovernmentOfficeRegion
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EastMidlands = 134370003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EastofEngland = 134370005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		London = 134370008,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NorthEast = 134370000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NorthWest = 134370001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SouthEast = 134370006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SouthWest = 134370007,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		WestMidlands = 134370004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		YorkshireandtheHumber = 134370002,
	}
}
#pragma warning restore CS1591
