#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HE.Investments.Common.CRM.Model
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum invln_ExternalStatus
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ApplicationDeclined = 858110012,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ApplicationSubmitted = 858110001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ApplicationUnderReview = 858110002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ApprovedSubjecttoContract = 858110014,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ApprovedSubjecttoDueDiligence = 858110011,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CashflowRequested = 858110006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CashflowUnderReview = 858110007,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ContractSignedSubjecttoCP = 858110015,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CPsSatisfied = 858110016,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Draft = 858110000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		HoldRequested = 858110004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InDueDiligence = 858110013,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		LoanAvailable = 858110017,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NA = 858110019,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		New = 858110018,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OnHold = 858110005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ReferredBacktoApplicant = 858110008,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SentforApproval = 858110010,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		UnderReview = 858110009,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Withdrawn = 858110003,
	}
}
#pragma warning restore CS1591
