#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HE.Investments.Common.CRM.Model
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum invln_ExternalStatusAHPOrganisation
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InvestmentPartnerFull = 858110000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InvestmentPartnerRestricted = 858110001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NotAnInvestmentPartner = 858110002,
	}
}
#pragma warning restore CS1591
