#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HE.Investments.Common.CRM.Model
{
	
	
	/// <summary>
	/// Device Event
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_DeviceEvent
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Case = 192350001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		IoTAlert = 192350000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		WorkOrder = 192350002,
	}
}
#pragma warning restore CS1591
