#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HE.Investments.Common.CRM.Model
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum mspp_ColumnPermissionValues
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Create = 746610000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Read = 746610001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Update = 746610002,
	}
}
#pragma warning restore CS1591
