#pragma warning disable CS1591
// Code Generated by DLaB.ModelBuilderExtensions
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum AIPluginType
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CustomConnector = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Dataverse = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SharedConnector = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Workflow = 4,
	}
}
#pragma warning restore CS1591
