#pragma warning disable CS1591
// Code Generated by DLaB.ModelBuilderExtensions
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Type of  channel activities.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum ConvertRule_ChannelActivity
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Appointment = 4201,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BookingAlert = 10711,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Conversation = 10454,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CopilotTranscript = 10909,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CustomerVoicealert = 10343,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CustomerVoicesurveyinvite = 10353,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CustomerVoicesurveyresponse = 10355,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Email = 4202,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Externalcomms = 11080,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		GovNotifyEmail = 11079,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InviteRedemption = 11008,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PhoneCall = 4210,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PortalComment = 11009,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ServiceActivity = 4214,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Session = 10471,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SocialActivity = 4216,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Task = 4212,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Teamschat = 10084,
	}
}
#pragma warning restore CS1591
