#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum he_HoweasywasittousetheCRM
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Difficulttouse = 134370001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Easytouse = 134370003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Neithereasynordifficult = 134370002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Verydifficulttouse = 134370000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Veryeasytouse = 134370004,
	}
}
#pragma warning restore CS1591
