#pragma warning disable CS1591
// Code Generated by DLaB.ModelBuilderExtensions
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum invln_AssessedforBHL
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NAmydevelopmentislessthan10homes = 858110002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		No = 858110001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Yes = 858110000,
	}
}
#pragma warning restore CS1591
