#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum invln_ConditionSource
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Bespoke = 858110001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Standard = 858110000,
	}
}
#pragma warning restore CS1591
