#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum invln_DefineTenure
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Affordablehome = 858110003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Affordablerent = 858110002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Marketrent = 858110001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Openmarket = 858110000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Other = 858110004,
	}
}
#pragma warning restore CS1591
