#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum invln_consortiumsingleentity
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Consortium = 858110000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SingleEntity = 858110001,
	}
}
#pragma warning restore CS1591
