#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum invln_EQRating
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EQ1EliminatediscriminationharassmentandvictimisationandanyotherconductthatisprohibitedundertheActEQ1 = 858110000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EQ2Advanceequalityofopportunitybetweenpersonswhosharerelevantequalitycharacteristicsandpersonswhodonotshareit = 858110001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EQ3Fostergoodrelationsbetweenpersonswhosharearelevantprotectedcharacteristicandpersonswhodonotshareit = 858110002,
	}
}
#pragma warning restore CS1591
