#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum invln_HAPPIprinciples
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AAdaptabilityandcarereadydesign = 858110000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BBalconiesandoutdoorspace = 858110001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CDaylightinthehomeandinsharedspaces = 858110002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DEnergyefficiencyandsustainabledesign = 858110003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EExternalsharedsurfacesandhomezones = 858110004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FPlantstreesandthenaturalenvironment = 858110005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		GPositiveuseofcirculationspace = 858110006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		HSharedfacilitiesandhubs = 858110007,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ISpaceandflexibility = 858110008,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		JStorageforbelongingsandbicycles = 858110009,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		KNone = 858110010,
	}
}
#pragma warning restore CS1591
