#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdynmkt_feature_state_option_set
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Disabled = 192350020,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Enabled = 192350010,
	}
}
#pragma warning restore CS1591
