#pragma warning disable CS1591
// Code Generated by DLaB.ModelBuilderExtensions
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Permission level can be individual or organization
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_smstemplate_permission
	{
		
		/// <summary>
		/// Individual
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Individual = 1,
		
		/// <summary>
		/// Organization
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Organization = 0,
	}
}
#pragma warning restore CS1591
