#pragma warning disable CS1591
// Code Generated by DLaB.ModelBuilderExtensions
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Enable appointments option set
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_enableappointmentsoption
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		No = 192350000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Yes = 192350001,
	}
}
#pragma warning restore CS1591
