#pragma warning disable CS1591
// Code Generated by DLaB.ModelBuilderExtensions
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyncrm_Fittype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Custom = 164230001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Fill = 164230000,
	}
}
#pragma warning restore CS1591
