# AHP-CRM-Deploy-UPGRADE

trigger:
- none
pr:
- none

schedules:
- cron: '0 1 * * 1,2,3,4,5'
  displayName: AHP - CRM - Deploy - Upgrade - Automatic night Deploy
  branches:
    include:
    - main

pool: 
  vmImage: windows-latest

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  branch: 'master'


resources:
  repositories:
  - repository: he-invst-deployment
    type: git
    name: 'Investments Programme/he-invst-deployment'
    ref: 'main'

stages:
- template: azure-pipelines-crm-ahp-build-export.yml@he-invst-deployment
- template: azure-pipelines-crm-ahp-upgrade.yml@he-invst-deployment
