trigger: none
pr: none

# schedules:
# - cron: '0 0 * * *'
#   displayName: Daily midnight build
#   branches:
#     include:
#     - development_R3

pool:
  vmImage: windows-latest

parameters:
  - name: buildAndUpdatePlugins
    displayName: Build & Update Plugins ?
    type: boolean
    default: true
  - name: buildAndUpdateWebResources
    displayName: Build & Update Webresources ?
    type: boolean
    default: true
  # - name: exportMigrationData
  #   displayName: Export Migration Data ?
  #   type: boolean
  #   default: false
  - name: exportEnvironmentVariables
    displayName: Export Environment Variables ?
    type: boolean
    default: true
  - name: exportMainSolution
    displayName: Export Main Solution ?
    type: boolean
    default: true
  - name: exportFlowsSolution
    displayName: Export Flows Solution ?
    type: boolean
    default: true
  - name: exportPluginsSolution
    displayName: Export Plugins Solution ?
    type: boolean
    default: true

variables:
  solution: "**/*.sln"
  buildPlatform: "Any CPU"
  buildConfiguration: "Release"
  branch: "development_R3"

resources:
  repositories:
    - repository: he-invst-deployment
      type: git
      name: "Investments Programme/he-invst-deployment"
      ref: "development_R3"

stages:
  - template: crm-deployment-pipelines/ahp-crm-build-export.yml@he-invst-deployment
    parameters:
      buildAndUpdatePlugins: "${{ parameters.buildAndUpdatePlugins }}"
      buildAndUpdateWebResources: "${{ parameters.buildAndUpdateWebResources }}"
      # exportMigrationData: "${{ parameters.exportMigrationData }}"
      exportEnvironmentVariables: "${{ parameters.exportEnvironmentVariables }}"
      exportMainSolution: "${{ parameters.exportMainSolution }}"
      exportFlowsSolution: "${{ parameters.exportFlowsSolution }}"
      exportPluginsSolution: "${{ parameters.exportPluginsSolution }}"
