# AHP-CRM-Deployment

trigger:
- none
pr:
- none

pool: 
  vmImage: windows-latest

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  branch: 'master'


resources:
  repositories:
  - repository: he-invst-deployment
    type: git
    name: 'Investments Programme/he-invst-deployment'
    ref: 'main'

stages:
- template: azure-pipelines-crm-ahp-deploy.yml@he-invst-deployment
