# AHP-CRM-Deploy-UPGRADE
trigger: none
pr: none

pool:
  vmImage: windows-latest

parameters:
- name: buildAndUpdatePlugins
  displayName: Build & Update Plugins ?
  type: boolean
  default: true
- name: buildAndUpdateWebResources
  displayName: Build & Update Webresources ?
  type: boolean
  default: true
- name: deployWithUpgrade
  displayName: Upgrade Solutions?
  type: boolean
  default: true
- name: deployMainSolution
  displayName: Deploy Main Solution ?
  type: boolean
  default: true
- name: deployFlowsSolution
  displayName: Deploy Flows Solution ?
  type: boolean
  default: true
- name: deployPluginsSolution
  displayName: Deploy Plugins Solution ?
  type: boolean
  default: true
- name: deployEnvironmentVariable
  displayName: Deploy Environment Variable ?
  type: boolean
  default: true

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  branch: 'master'

resources:
  repositories:
  - repository: he-invst-deployment
    type: git
    name: 'Investments Programme/he-invst-deployment'
    ref: 'main'
    pipelines:
    - pipeline: BuildPipeline

stages:
- template: azure-pipelines-crm-ahp-build-export.yml@he-invst-deployment
  parameters:
    buildAndUpdatePlugins: '${{ parameters.buildAndUpdatePlugins }}'
    buildAndUpdateWebResources: '${{ parameters.buildAndUpdateWebResources }}'
    deployMainSolution: '${{ parameters.deployMainSolution }}'
    deployFlowsSolution: '${{ parameters.deployFlowsSolution }}'
    deployPluginsSolution: '${{ parameters.deployPluginsSolution }}'
    deployEnvironmentVariable: '${{ parameters.deployEnvironmentVariable }}'


- template: azure-pipelines-crm-ahp-upgrade.yml@he-invst-deployment
  parameters:
    artifactLocationPipeline: BuildPipeline
    deployWithUpgrade: '${{ parameters.deployWithUpgrade }}'
    deployMainSolution: '${{ parameters.deployMainSolution }}'
    deployFlowsSolution: '${{ parameters.deployFlowsSolution }}'
    deployPluginsSolution: '${{ parameters.deployPluginsSolution }}'
    deployEnvironmentVariable: '${{ parameters.deployEnvironmentVariable }}'
