# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pr:
  branches:
    include:
    - development_R3
  paths:
    include:
    - src/HE.UtilsService/*

pool:
  vmImage: 'ubuntu-22.04'

resources:
  repositories:
  - repository: he-invst-deployment
    type: git
    name: 'Investments Programme/he-invst-deployment'
    ref: 'feature/104413_Rename_DocumentService_to_UtilsService_'
  - repository: templates
    type: git
    name: 'Cloud Hosting Service/Templates'
    ref: 'master'

stages:
- template: portal-deployment-pipelines/azure-pipelines-utils-service-build.yml@he-invst-deployment
