# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

#trigger:
#  branches:
#    include:
#    - 'main'
#  paths:
#    include:
#    - src/HE.DocumentService/*
 
trigger:
  branches:
    include:
    - feature*/*
  paths:
    include:
    - src/HE.DocumentService/*

pool: "vmss-ado-chs-nonprod-001"
          
resources:
  repositories:
  - repository: he-invst-deployment
    type: git
    name: 'Investments Programme/he-invst-deployment'
    ref: 'main'
  - repository: templates
    type: git
    name: 'Cloud Hosting Service/Templates'
    ref: 'master'

stages:
- template: azure-pipelines-document-service-build.yml@he-invst-deployment
