#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HE.Investments.Common.CRM.Model
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("invln_setallocationphase")]
	public partial class invln_setallocationphaseRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string invln_allocationid = "invln_allocationid";
			public const string invln_accountid = "invln_accountid";
			public const string invln_userid = "invln_userid";
			public const string invln_deliveryphaseid = "invln_deliveryphaseid";
			public const string invln_phaseclaimsdto = "invln_phaseclaimsdto";
		}
		
		public const string ActionLogicalName = "invln_setallocationphase";
		
		public System.Guid invln_allocationid
		{
			get
			{
				if (this.Parameters.Contains("invln_allocationid"))
				{
					return ((System.Guid)(this.Parameters["invln_allocationid"]));
				}
				else
				{
					return default(System.Guid);
				}
			}
			set
			{
				this.Parameters["invln_allocationid"] = value;
			}
		}
		
		public System.Guid invln_accountid
		{
			get
			{
				if (this.Parameters.Contains("invln_accountid"))
				{
					return ((System.Guid)(this.Parameters["invln_accountid"]));
				}
				else
				{
					return default(System.Guid);
				}
			}
			set
			{
				this.Parameters["invln_accountid"] = value;
			}
		}
		
		public string invln_userid
		{
			get
			{
				if (this.Parameters.Contains("invln_userid"))
				{
					return ((string)(this.Parameters["invln_userid"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["invln_userid"] = value;
			}
		}
		
		public System.Guid invln_deliveryphaseid
		{
			get
			{
				if (this.Parameters.Contains("invln_deliveryphaseid"))
				{
					return ((System.Guid)(this.Parameters["invln_deliveryphaseid"]));
				}
				else
				{
					return default(System.Guid);
				}
			}
			set
			{
				this.Parameters["invln_deliveryphaseid"] = value;
			}
		}
		
		public string invln_phaseclaimsdto
		{
			get
			{
				if (this.Parameters.Contains("invln_phaseclaimsdto"))
				{
					return ((string)(this.Parameters["invln_phaseclaimsdto"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["invln_phaseclaimsdto"] = value;
			}
		}
		
		public invln_setallocationphaseRequest()
		{
			this.RequestName = "invln_setallocationphase";
			this.invln_allocationid = default(System.Guid);
			this.invln_accountid = default(System.Guid);
			this.invln_userid = default(string);
			this.invln_deliveryphaseid = default(System.Guid);
			this.invln_phaseclaimsdto = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("invln_setallocationphase")]
	public partial class invln_setallocationphaseResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string id = "id";
		}
		
		public const string ActionLogicalName = "invln_setallocationphase";
		
		public invln_setallocationphaseResponse()
		{
		}
		
		public System.Guid id
		{
			get
			{
				if (this.Results.Contains("id"))
				{
					return ((System.Guid)(this.Results["id"]));
				}
				else
				{
					return default(System.Guid);
				}
			}
		}
	}
}
#pragma warning restore CS1591
