namespace HE.InvestmentLoans.Contract.Projects;
public enum ProjectState : int
{
    Index = 1,
    Name,
    StartDate,
    ManyHomes,
    TypeHomes,
    PlanningRef,
    PlanningRefEnter,
    CheckPlanning,
    PlanningPermissionStatus,
    Location,
    ProvideLocalAuthority,
    LocalAuthorityResult,
    LocalAuthorityConfirm,
    LocalAuthorityReset,
    Ownership,
    Additional,
    GrantFunding,
    GrantFundingMore,
    AffordableHomes,
    CheckAnswers,
    Complete,
    Type,
    ChargesDebt,
    DeleteProject,
    TaskList,
}
