namespace HE.Investment.AHP.Domain.HomeTypes;

public enum HomeTypesWorkflowState
{
    Index = 1,
    List,
    RemoveHomeType,
    FinishHomeTypes,
    NewHomeTypeDetails,
    HomeTypeDetails,
    HomeInformation,
    HomesForDisabledPeople,
    DisabledPeopleClientGroup,
    HomesForOlderPeople,
    HappiDesignPrinciples,
    DesignPlans,
    SupportedHousingInformation,
    RevenueFunding,
    ExitPlan,
    MoveOnArrangements,
    TypologyLocationAndDesign,
    MoveOnAccommodation,
    PeopleGroupForSpecificDesignFeatures,
    BuildingInformation,
    BuildingInformationIneligible,
    CustomBuildProperty,
    TypeOfFacilities,
    AccessibilityStandards,
    AccessibilityCategory,
    CheckAnswers,
}
