trigger: none
pr: none

pool:
  vmImage: windows-latest

parameters:
  - name: mainSolutionName
    displayName: Main Solution name
    type: string
    default: 'InvestmentsLoansReleaseFixesv1_2'

variables:
  solution: "**/*.sln"
  buildPlatform: "Any CPU"
  buildConfiguration: "Release"
  branch: "master"

resources:
  repositories:
    - repository: he-invst-deployment
      type: git
      name: "Investments Programme/he-invst-deployment"
      ref: "hotfix_managed_unamanged_paths"

stages:
  - template: crm-deployment-pipelines/hotfix-crm-build-export.yml@he-invst-deployment
    parameters:
      exportMainSolution: true
      mainSolutionName: "${{ parameters.mainSolutionName }}"
