trigger: none
pr: none

pool:
  vmImage: windows-latest

parameters:
- name: mainSolutionName
  displayName: Main Solution name
  type: string
  default: 'InvestmentsLoansReleaseFixesv2_0'

variables:
  solution: "**/*.sln"
  buildPlatform: "Any CPU"
  buildConfiguration: "Release"
  branch: "master"

resources:
  repositories:
  - repository: he-invst-deployment
    type: git
    name: "Investments Programme/he-invst-deployment"
    ref: "main"

stages:
- template: crm-deployment-pipelines/hotfix-crm-deploy-nonprod.yml@he-invst-deployment
  parameters:
    deployMainSolution: true
    mainSolutionName: "${{ parameters.mainSolutionName }}"
