trigger: none
pr: none

pool:
  vmImage: windows-latest

schedules:
- cron: '30 4 * * 1,3,5'
  displayName: '04:30 AM - Mon, Wed, Fri Solution Export'
  branches:
    include:
    - development_R3
  always: true
  batch: true

parameters:
  - name: buildAndUpdatePlugins
    displayName: Build & Update Plugins ?
    type: boolean
    default: true
  - name: buildAndUpdateWebResources
    displayName: Build & Update Webresources ?
    type: boolean
    default: true
  - name: exportEnvironmentVariables
    displayName: Export Environment Variables ?
    type: boolean
    default: true
  - name: exportMainSolution
    displayName: Export Main Solution ?
    type: boolean
    default: true
  - name: exportFlowsSolution
    displayName: Export Flows Solution ?
    type: boolean
    default: true
  - name: exportPluginsSolution
    displayName: Export Plugins Solution ?
    type: boolean
    default: true

variables:
  solution: "**/*.sln"
  buildPlatform: "Any CPU"
  buildConfiguration: "Release"
  branch: "master"

resources:
  repositories:
    - repository: he-invst-deployment
      type: git
      name: "Investments Programme/he-invst-deployment"
      ref: "development_R3"

stages:
  - template: crm-deployment-pipelines/invst-R3-crm-build-export.yml@he-invst-deployment
    parameters:
      buildAndUpdatePlugins: "${{ parameters.buildAndUpdatePlugins }}"
      buildAndUpdateWebResources: "${{ parameters.buildAndUpdateWebResources }}"
      exportEnvironmentVariables: "${{ parameters.exportEnvironmentVariables }}"
      exportMainSolution: "${{ parameters.exportMainSolution }}"
      exportFlowsSolution: "${{ parameters.exportFlowsSolution }}"
      exportPluginsSolution: "${{ parameters.exportPluginsSolution }}"
