# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  batch: true
  branches:
    include:
    - development_R3
  paths:
    include:
    - src/HE.InvestmentLoans.sln
    - src/HE.Investments.Loans.*/*
    - src/HE.Investments.FrontDoor.Shared/*
    - src/HE.Investments.Account.Shared/*
    - src/HE.Investments.Account.Api.Contract/*
    - src/HE.Investments.Common*/*
    - src/HE.Common.*/*
    - src/HE.Investments.DocumentService/*
    - src/HE.Investments.IntegrationTestsFramework/*
    - src/HE.Investments.Organisation/*
    - src/HE.Investments.TestsUtils/*
    - src/He.AspNetCore.Mvc.Gds.Components/*
    - src/HE.Investments.FrontDoor.Shared/*
    - src/HE.Investments.Api/*

pr:
  branches:
    include:
    - development_R3
  paths:
    include:
    - src/HE.InvestmentLoans.sln
    - src/HE.Investments.Loans.*/*
    - src/HE.Investments.Account.Shared/*
    - src/HE.Investments.Account.Api.Contract/*
    - src/HE.Investments.Common*/*
    - src/HE.Common.*/*
    - src/HE.Investments.DocumentService/*
    - src/HE.Investments.IntegrationTestsFramework/*
    - src/HE.Investments.Organisation/*
    - src/HE.Investments.TestsUtils/*
    - src/He.AspNetCore.Mvc.Gds.Components/*
    - src/HE.Investments.FrontDoor.Shared/*
    - src/HE.Investments.Api/*

parameters:
  - name: forcePushToProd
    displayName: Force Push to Production
    type: boolean
    default: false

variables:
  buildMajor: 0
  buildMinor: 0
  buildBranch: $[replace(variables['Build.SourceBranch'], '/', '.')]

pool:
  vmImage: 'ubuntu-22.04'

name: $(buildMajor).$(buildMinor).$(Rev:r)-loans.$(buildBranch)


resources:
  repositories:
  - repository: he-invst-deployment
    type: git
    name: 'Investments Programme/he-invst-deployment'
    ref: 'feature/semver'
  - repository: templates
    type: git
    name: 'Cloud Hosting Service/Templates'
    ref: 'master'

stages:
- template: portal-deployment-pipelines/azure-pipelines-loans-portal-build.yml@he-invst-deployment
