# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  batch: true
  branches:
    include:
      - main
  paths:
    exclude:
      - src/HE.DocumentService/*

pr:
  branches:
    include:
      - main
  paths:
    exclude:
      - src/HE.DocumentService/*

pool: "vmss-ado-chs-nonprod-001"

resources:
  repositories:
  - repository: he-invst-deployment
    type: git
    name: 'Investments Programme/he-invst-deployment'
    ref: 'main'
  - repository: templates
    type: git
    name: 'Cloud Hosting Service/Templates'
    ref: 'master'

stages:
- template: azure-pipelines-loans-portal-build.yml@he-invst-deployment
