#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("invln_deleteloanapplication")]
	public partial class invln_deleteloanapplicationRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string invln_loanapplicationid = "invln_loanapplicationid";
		}
		
		public const string ActionLogicalName = "invln_deleteloanapplication";
		
		public string invln_loanapplicationid
		{
			get
			{
				if (this.Parameters.Contains("invln_loanapplicationid"))
				{
					return ((string)(this.Parameters["invln_loanapplicationid"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["invln_loanapplicationid"] = value;
			}
		}
		
		public invln_deleteloanapplicationRequest()
		{
			this.RequestName = "invln_deleteloanapplication";
			this.invln_loanapplicationid = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("invln_deleteloanapplication")]
	public partial class invln_deleteloanapplicationResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public const string ActionLogicalName = "invln_deleteloanapplication";
		
		public invln_deleteloanapplicationResponse()
		{
		}
	}
}
#pragma warning restore CS1591
