#pragma warning disable CS1591
// Code Generated by DLaB.ModelBuilderExtensions
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("invln_getabsoluteahpapplicationfilelocation")]
	public partial class invln_getabsoluteahpapplicationfilelocationRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string invln_applicationid = "invln_applicationid";
		}
		
		public const string ActionLogicalName = "invln_getabsoluteahpapplicationfilelocation";
		
		public string invln_applicationid
		{
			get
			{
				if (this.Parameters.Contains("invln_applicationid"))
				{
					return ((string)(this.Parameters["invln_applicationid"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["invln_applicationid"] = value;
			}
		}
		
		public invln_getabsoluteahpapplicationfilelocationRequest()
		{
			this.RequestName = "invln_getabsoluteahpapplicationfilelocation";
			this.invln_applicationid = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("invln_getabsoluteahpapplicationfilelocation")]
	public partial class invln_getabsoluteahpapplicationfilelocationResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string invln_documentlocation = "invln_documentlocation";
		}
		
		public const string ActionLogicalName = "invln_getabsoluteahpapplicationfilelocation";
		
		public invln_getabsoluteahpapplicationfilelocationResponse()
		{
		}
		
		public string invln_documentlocation
		{
			get
			{
				if (this.Results.Contains("invln_documentlocation"))
				{
					return ((string)(this.Results["invln_documentlocation"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
}
#pragma warning restore CS1591
